mysite/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('introduce/', views.introduce, name="introduce"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:delete_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/edit/', views.edit, name="edit"),
    path('<int:article_pk>/update/', views.update, name="update"),
]

mysite/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model): # articles_article
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) # 자동으로 생성되는 시간 추가
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title} : {self.content}'
        

mysite/articles/views.py
from django.shortcuts import render, redirect
# 모델 가져오기
from .models import Article

# Create your views here.
def index(request):
     # 전체 데이터 가져오기
    articles = Article.objects.all()[::-1]
    # 그 데이터를 템플릿에게 넘겨주기
    context = {
        'articles' : articles
    }
    
    # 템플릿에서 반복문으로 각각의 게시글의 pk, title 보여주기
    return render(request, 'articles/index.html',context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    # 데이터 생성을 위한 ORM 활용
    # 첫번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 어떤 방식을 사용했는가에 따라서
    # SAVE() 메서드를 사용할 것인지 아닌지
    # 두번째 방법
    # article = Article(title=title,content=content)
    # article.save()
    article = Article.objects.create(title=title,content=content)
    # context = {
    #     'title' : title,
    #     'content' : content
    # }
    # return render(request, 'articles/index.html', context)
    return redirect('articles:index')

def introduce(request):
    return render(request, 'articles/introduce.html')

# 1. 상세 페이지를 보기 위한 경로
# 1-1. 특정 게시들에 대한 고유 값
# 1-2. /articles/1/, /articles/2/
# 2. 해당 게시글에 대한 상세 내용
# 3. 인덱스 페이지로 돌아가는 링크

def detail(request,article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article 
    }
    return render(request, 'articles/detail.html',context)

# 1. 특정 글 삭제를 위한 경로 작성
# 1-1. /articles/1/delete
# 2. 글 삭제 처리를 해주는 View 작성
# 3. 글 삭제 후, index page로 redirect
# 4. 글 삭제를 위한 링크 detail에 작성
def delete(request, delete_pk):
    article = Article.objects.get(pk=delete_pk)
    if request.method == "POST":
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', delete_pk)

# 1. 특정 글 수정을 위한 경로 생성
# 1-1. /articles/1/edit/
# 2. 글 수정 template를 render하는 edit view 작성
# 2-1. 해당 template에 form tag 작성
# 2-3. 각 input tag 내부에 기존 내용이 들어있어야 함.
# 2-3. value 속성을 활용
def edit(request,article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article
    }
    return render(request,'articles/edit.html',context)

# update
# 3. edit에서 보낸 데이터 처리를 위한 경로 생성
# 3-1. /articles/1/update
# 4. 글 수정 처리를 하는 update view 작성
# 5. 해당 글 상세 페이지로 redirect
# 6. 글 수정을 위한 edit 링크 상세 페이지 설정
# 6-1. {% url 'articles:edit' article.pk %}
def update(request,article_pk):
    article = Article.objects.get(pk=article_pk)
    title = request.POST.get('title')
    content = request.POST.get('content')
    article.title = title
    article.content = content
    article.save()
    return redirect('articles:detail',article_pk)

mysite/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block body %}

<h1> 글 작성 완료 </h1>
<hr>
<h2> 글 제목은 {{title}} </h2>
<p> 본문은 {{content}} </p>
<hr>
<a href="{% url 'articles:index' %}">back</a>
{% endblock %}

mysite/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
<h1> 세부 내용 </h1>
<hr>
<p>{{article.pk}}번째 글 </p>
<p>제목 : {{article.title}}</p>
<p>내용 : {{article.content}}</p>
<p>생성 시간 : {{article.created_at}}</p>
<p>수정 시간 :{{article.updated_at}}</p>

<a href="{% url 'articles:index' %}">back</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST"> 
  {% csrf_token %}
  <input type="submit" value="delete">
</form>
<br>
<a href="{% url 'articles:edit' article.pk %}"> 수정 </a> 
{% endblock %}

mysite/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block body %}
<h1> 글 수정하기 </h1>
<form action="{% url 'articles:update' article.pk %}" method="POST">
{% csrf_token %}
<p>{{article.pk}}</p>
<p><stroing>제목 : </stroing><input type="text" id="title" name ="title" value={{article.title}}></p>
<label for="cnt">내용 : </label> 
<textarea name = "content" id="cnt" cols="30" rows="10">
  {{ article.content }}
</textarea> 
<input type="submit" value="글 수정">
</form>
{% endblock %}

mysite/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
  <h1> 게시판 </h1>
  <hr>
  <a href="{% url 'articles:new' %}"> NEW </a>
  <a href="{% url 'articles:introduce' %}"> Introduce </a>
  <hr>
  {% for article in articles %}
    <a href="{% url 'articles:detail' article.pk %}"><h3>{{article.pk}}</h3></a>
    <a href="/articles/{{ article.pk }}"><p>{{article.title}}</p> </a>
    <p>{{article.content}}</p>
    <hr>
  {% endfor %}
{% endblock %}

mysite/articles/templates/articles/introduce.html
{% extends 'base.html' %}
{% block body %}
<h1> 소개 페이지 </h1>
<hr>
<p> 나의 이름은 윤소윤 </p>
<p> 나의 나이는 ??? </p>
<a href="{% url 'articles:index' %}"> back </a>

{% endblock %}

mysite/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block body %}
<h1> 글 작성 페이지 </h1>
<hr>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <label for="name">제목 : </label>
  <input type="text" id="name" name="title" placeholder="내용을 입력해주세요"><br/>
  <label for="cnt">내용 : </label>
  <textarea name="content" id="cnt" cols="40" rows="10">
    여기에 내용을 입력해 주세요.
  </textarea>

  <input type="submit" value="글 작성">
</form>
{% endblock %}