django_relation/mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"), 
    path('follow/<int:user_pk>/', views.follow , name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

django_relation/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_relation/mysite/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser



# Usercustomizing
class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="followings",
        blank=True,
    )


    # 각종 필드 추가
    # createsuperuser - 비어있는 계정 있어서 추가할 수 없다.
    # shell_plus => create_user, is_staff, 최고 권한 True

django_relation/mysite/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail



# Create your models here.

def articles_image_path(instance, filename):
    return f'user_{instance.user.pk}/{filename}'

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    # blank - 유효성 검사 시
    # null - DB상의 컬럼의 Null
    image = models.ImageField(blank=True, upload_to="%y/%m/%d/") # 업로드 날짜별 저장
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200,300)],
        format='JPEG',
        options={'quality':90},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
     # 게시글 좋아요
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_articles',
        blank=True) # 게시글에 좋아요 없는 유효성 검사 통과할 수 있도록 blank=True 걸어준다.
    recommend_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='recommend_articles',
        blank=True)


    # Article이 호출되었을 때 출력되는 내용 - magic method
    def __str__(self):
        return f'{self.pk}번째 글, {self.title}-{self.content}'

class Comment(models.Model):
    # 멤버 변수 = models.외래키(참조하는 객체, 삭제 되었을 때 처리 방법[on_delete])
    article = models.ForeignKey(to=Article, on_delete=models.CASCADE)
    # 역참조 값 설정 related_name = 'comments'
    content = models.CharField(max_length=200)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   
    

    def __str__(self):
        return f'Article:{self.article},{self.pk}-{self.content}'

django_relation/mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm , PasswordChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


# 항상 활성화된 모델
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # username은 unique하기 때문에 수정하지 않는다.
        fields = ['email', 'first_name', 'last_name',]

class UserPassChangeForm(PasswordChangeForm):
    class Meta:
        model = get_user_model()
        fields =  ['password',]

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        # fields =

django_relation/mysite/accounts/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# from django.contrib.auth import UserChangeForm as CustomUserChangeForm
# views.py 내 정의한 함수 login과 구분하기 위해 auth_log로 재 명명함
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import CustomUserChangeForm ,CustomUserCreationForm
from .forms import UserPassChangeForm

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST) # request : 요청 파라미터
            # AuthenticationForm은 ModelForm이 아닌 Form 상속
            # 별도로 정의된 Model이 없다는 뜻
            # 그래서 넘겨주는 인자가 달라진다.
        if form.is_valid():
            # 로그임은 DB에 뭔가 작성하는 것은 동일하지만, 
            # 연결된 모델이 있는 건 아닙니다.
            # 그럼 무엇을 확인해야 하는가?  - 세션과 유저 정보
            auth_login(request, form.get_user()) 
            return redirect("articles:index")
    else:
        if request.user.is_authenticated :
            return redirect("articles:index")
        else:
            form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, "accounts/form.html", context )

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST) # 사용자가 POST방식으로 보내온 정보를 담아서 form 생성
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:login")

    else:
        form = CustomUserCreationForm() # 인스턴스화
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect("articles:index")

# 회원 삭제
@require_POST # 삭제는 POST일 때만 가능 - get방식으로 들어 왔을 때는 405에러 
def delete(request):
    request.user.delete()  # request안에 요청을 보낸 user의 데이터가 들어있어서 다른 매개변수는 필요 없다.
    return redirect('articles:index')

def update(request):
    if request.method =="POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            return redirect("articles:index")
    else:
        form =  CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

@login_required
def password(request):
    if request.method == "POST":
        form = UserPassChangeForm(request.user, request.POST) # 순서 꼭 지키기
        if form.is_valid():
            user = form.save()
            # auth_login(request, user) - 저장되어있던 session이 바뀌고 새로운 session을 만든다.
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = UserPassChangeForm(request.user)
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)# 특정 유저 정보 받아오기
    context={
        'person' : person
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, user_pk ):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    user = request.user
    # 원래 person에 담긴 user_pk값을 가진 유저는 프로필의 주인이다.
    # request.user는 나, 요청을 보내온 사용자이다.
    if user in person.followers.all():
        person.followers.remove(user)        
    else:
        person.followers.add(user)     
    return redirect('accounts:profile', person.username)
    
    
    

django_relation/mysite/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% block body %}
{% if request.resolver_match.url_name == 'login' %}
<h1> 로그인</h1>
{% elif request.resolver_match.url_name == 'signup' %}
<h1> 회원가입</h1>
{% elif request.resolver_match.url_name == 'password' %}
<h1> 비밀번호 수정</h1>
{% else %}
<h1> 회원정보 수정</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="OK" class="btn btn-info">
</form>
{% endblock %}

django_relation/mysite/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<h1> 로그인</h1>
<form action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="로그인">
</form>
<a href="{% url 'accounts:signup' %}"> 회원가입</a>
{% endblock %}

django_relation/mysite/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% block body %}
<form action="{% url 'accounts:password' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="변경">
</form>

{% endblock %}

django_relation/mysite/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
<h1> {{ person.username }} </h1>
{% if user != person %}
  {% if user in person.followers.all %}
  <a href="{% url 'accounts:follow' person.pk %}"> <i class="fas fa-user-plus"> follow </i></a>  
  {% else %}
  <a href="{% url 'accounts:follow' person.pk %}"><i class="fas fa-handshake-slash"> cancel </i> </a> 
  {% endif %}
{% endif %}
<hr>
{{ person.first_name }}
{{ person.last_name }}
{{ person.email }}

<!--person : 프로필이 생성될 때 보내진 값  (팔로우 되는 사람)
    user : 로그인 되어 있는 사람
      -->


{% for article in person.article_set.all %}
{{ article.title }} / {{ article.content }} 
{% endfor %}

{% for comment in person.coment_set.all %}
{{ comment.title }} / {{ comment.content }}
{% empty %}
<p> 댓글을 단 적이 없습니다.</p> 
{% endfor %}


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">유저가 작성한 게시글</th>
      <th scope="col">제목</th>
      <th scope="col">내용</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">유저가 작성한 댓글</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>
<!-- 유저가 좋아요 누른 게시글 -->
{% for like in person.like_articles.all %}
{{ like.name }}
{% empty %}
<p> 좋아요를 누른 게시글이 없습니다. </p> 
{% endfor %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>

{% endblock %}

django_relation/mysite/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block body %}
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="등록">
</form>
{% endblock %}

django_relation/mysite/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block body %}
<form action="{% url 'accounts:update' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="수정">
</form>
{% endblock %}