django_relation/mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"), 
    path('follow/<int:user_pk>/', views.follow , name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

django_relation/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_relation/mysite/mysite/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <script src="https://kit.fontawesome.com/7d9d1fe263.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <title>Document</title>
</head>

<body>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}" role="alert">
    {{ message.message }}
  </div>
  {% endfor %}
  {% endif %}
  <div style="float: right;">
    <ul class="nav nav-pills">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link " href="{% url 'accounts:profile' user.username %}" tabindex="-1" >{{ user.username }}님 환영합니다</a>
      </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'accounts:update' %}">회원정보 수정</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
      {% endif %}
    </ul>
  </div>
  <br/><br/>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>

</html>