django_relation/mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"), 
    path('follow/<int:user_pk>/', views.follow , name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

django_relation/mysite/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/insert/', views.insert, name="insert"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
]

django_relation/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_relation/mysite/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail



# Create your models here.

def articles_image_path(instance, filename):
    return f'user_{instance.user.pk}/{filename}'

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    # blank - 유효성 검사 시
    # null - DB상의 컬럼의 Null
    image = models.ImageField(blank=True, upload_to="%y/%m/%d/") # 업로드 날짜별 저장
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200,300)],
        format='JPEG',
        options={'quality':90},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
     # 게시글 좋아요
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_articles',
        blank=True) # 게시글에 좋아요 없는 유효성 검사 통과할 수 있도록 blank=True 걸어준다.
    recommend_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='recommend_articles',
        blank=True)


    # Article이 호출되었을 때 출력되는 내용 - magic method
    def __str__(self):
        return f'{self.pk}번째 글, {self.title}-{self.content}'

class Comment(models.Model):
    # 멤버 변수 = models.외래키(참조하는 객체, 삭제 되었을 때 처리 방법[on_delete])
    article = models.ForeignKey(to=Article, on_delete=models.CASCADE)
    # 역참조 값 설정 related_name = 'comments'
    content = models.CharField(max_length=200)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   
    

    def __str__(self):
        return f'Article:{self.article},{self.pk}-{self.content}'

django_relation/mysite/articles/forms.py
from django import forms
from .models import Article, Comment # models에서 객체 호출

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        #fields = '__all__'
        exclude = ['user','like_users', 'recommend_users']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__' #  __all__ : 전체 게시글 연결
        # fields = ['content'] 이렇게 작성하기에는 양이 너무 방대함.
        exclude = ['article', 'user'] # article만 제외하고 연결시킨다. 

django_relation/mysite/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
# DVDH
# Django가 주는 views에서 쓸 decorators http를 위함
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from IPython import embed # idex로 들어오면 embed 함수 실행
from django.contrib import messages
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    articles = Article.objects.all()
    # 1. Paginator(전체 리스트, 한 페이지당 갯수)
    paginator = Paginator(articles, 3)  # List, sequence
    # 2. 몇 번째 페이지를 보여줄 것인지 GET으로 받기
    # 'articles/?page=3
    page = request.GET.get('page')
    # 해당하는 페이지의 게시글만 가져오기      
    articles = paginator.get_page(page)
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    comments = article.comment_set.all() # 특정 article이 가지고 있는 댓글 조회
    # 1: N을 보장할 수 없기 때문에 querySet(commet_set)형태로 조회해야 한다.
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments' : comments
    }
    return render(request, 'articles/detail.html', context)

@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)  # request.POST : 사용자가 보낸 제목, 내용이 들어있음 -> 파일도 추가해주어야 한다.(request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, '게시글 작성 완료!')
            return redirect('articles:detail', article.pk)
        else : 
            messages.error(request, '잘못된 데이터 입력!')
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user :
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article.user = request.user
                article = form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form
        }
        return render(request, 'articles/form.html', context)
    else :
        return redirect('articles:detail', article.pk)

    
@login_required
def delete(request, article_pk):   
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
            return redirect('articles:index')
        else:
            return redirect('articles:detail', article.pk)
        return redirect('articles:index')
        



# def comment_delete(request, article_pk, comment_pk):
#     # article_id: 게시글에 대한 pk 값
#     comment = get_object_or_404(Comment, pk=comment_pk) # Comment : model에서 정의한 class
#     if request.method == "POST":
#         comment.delete()
#     return redirect('articles:detail', article_pk) # comment.article.pk - OK

@login_required
@require_POST
def comment_delete(request, article_pk, comment_pk):    
    comment = get_object_or_404(Comment, pk=comment_pk) # Comment : model에서 정의한 class
    comment.delete()
    return redirect('articles:detail', article_pk) # comment.article.pk - OK


@require_POST
@login_required
def insert(request, article_pk):
    # article = Article.objects.get(pk=article_id)
    article = get_object_or_404(Article, pk = article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)   # 이로서 접근 권한이 생김
        # commit=False ?  생성은 하지만 DB에 반영은 하지 않는다 default는 True 
        # comment = article.comment_set.all() 
        #comment.article_id = article.pk
        comment.user = request.user 
        comment.article = article
        comment.save()
        return redirect('articles:detail', article.pk)
    else:
        context = {
            'comment_form': focomment_form,
            'article' : article
        }
    return render(request, 'articles/detail.html', context)

@login_required
def like(request, article_pk):
    # 특정 게시물에 대한 정보
    article = get_object_or_404(Article, pk=article_pk)
    # 좋아요를 누른 유저에 대한 정보
    user = request.user
    # 사용자가 게시글의 좋아요 목록에 있으면,
    if user in article.like_users.all(): #user가 sequence안에 있는지 확인 - 있으면 좋아요 취소
        article.like_users.remove(user)
        liked = False
    else:
        article.like_users.add(user)
        liked = True
    context = {
        'liked':liked,
        'count': article.like_users.count()
    }
    return JsonResponse(context)


@login_required
def recommend(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if user in article.recommend_users.all():
        article.recommend_users.remove(user)
    else:
        article.recommend_users.add(user)
    return redirect('articles:index')

django_relation/mysite/articles/templates/articles/_like.html
{% if user in article.like_users.all %}
<i class="fas fa-heart fa-lg like-button" data-id="{{ article.id }}" style="color: crimson;"></i>
{% else %}
<i class="far fa-heart fa-lg like-button" data-id="{{ article.id }}" style="color:black;"></i>
{% endif %}
<span id="like-count-{{ article.pk }}"> {{ article.like_users.count }}</span> 

{% if user in article.recommend_users.all %}
<i class="fas fa-comments"></i> {{ article.comment_set.all|length }} <a href="{% url 'articles:recommend' article.pk %}"><i class="far fa-thumbs-up text-danger"></a></i> {{ article.recommend_users.all|length }}
{% else %}
<i class="fas fa-comments"></i> {{ article.comment_set.all|length }} <a href="{% url 'articles:recommend' article.pk %}"><i class="far fa-thumbs-up text-info"></a></i> {{ article.recommend_users.all|length }}
{% endif %}

django_relation/mysite/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>상세 페이지</h1>
<hr><hr>

<storing><<{{ article.pk }}>></strong>
<p> 작성자 | {{article.user.username }}</p>

{% if user in article.recommend_users.all %}
<a href="{% url 'articles:recommend' article.pk %}">추천</a>
{% else %}
<a href="{% url 'articles:recommend' article.pk %}">추천 취소</a>
{% endif %}

<h1>{{ article.title }}</h1>
<h4>{{ article.content }}</h4>

{% if article.image %}
<img src ="{{ article.image_thumbnail.url }}" alt="{{ article.image }}">
{% else %}
<img src="" alt="">
{% endif %}
{% include 'articles/_like.html' %}
<hr>
<form action="{% url 'articles:insert' article.pk %}" method="POST">
  {% csrf_token %}
  {{ comment_form }}
  <input type ="submit" value="댓글 생성">
</form>

<P>댓글 총 {{ comments|length }} 개</P>
<!-- <P>댓글 총 {{ article.comment_set.all|length }} 개</P> -->

{% for comment in comments %}
    <strong>{{ comment.pk}} </strong>{{ comment.content }} 작성자 | {{ comment.user.username }}
    <!-- 2 개 이상의 값을 넘겨주고자 할 때 순서 주의 !! -->
    <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="댓글 삭제" class="btn btn-danger">
    </form> 
{% empty %}
  <p>댓글이 존재하지 않습니다.</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">[수정]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제" class="btn btn-primary">
    </form>
  {% endif %}
{% endif %}

<a href="{% url 'articles:index' %}">[BACK]</a>

<script src="{% static 'articles/js/like.js' %}"></script>
{% endblock %}

django_relation/mysite/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
{% else %}
  <h1>글 수정</h1>
{% endif %}

<hr>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

  <a href="{% url 'articles:index' %}">[BACK]</a>

{% endblock %}

django_relation/mysite/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>메인 페이지 입니다.</h1>
<hr>
{% if user.is_authenticated %}
<div style="float: right;">
  <a href="{% url 'articles:create' %}" class="btn btn-info">글 생성</a>
</div>
{% endif %}
<table class="table" style="margin-top: 10px;">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">제목</th>
      <th scope="col">작성자</th>
      <th scope="col">비고</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{ article.pk }}</th>
      <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a> 
      </td>
      <td><a href="{% url 'accounts:follow' article.user.pk %}">{{ article.user.username }}</a></td>
      <td>
        {% include 'articles/_like.html' %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
 <hr>
  {% for num in articles.paginator.page_range %}
  <a href="{% url 'articles:index' %}?page={{ num }}">{{ num }}</a>
  {% endfor %}
  <script src="{% static 'articles/js/like.js' %}"></script>
{% endblock %}